rigueira/core/urls.py
from core.forms import AuthenticationForm
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import home

urlpatterns = [
    path(
        '',
        auth_views.LoginView.as_view(
            template_name='core/login.html',
            authentication_form=AuthenticationForm,
        ),
        name='login',
    ),
    path('home', home, name='home'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
]

rigueira/feedback/urls.py
from django.urls import path

from .views import dashboard

app_name = 'feedback'
urlpatterns = [path('dashboard', dashboard, name='dashboard')]

rigueira/rigueira/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from rigueira import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
]


if settings.DEBUG == 'True':
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

rigueira/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

core/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models


# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("O email é obrigatório!")
        user = self.model(email=self.normalize_email(email), **extra_fields)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        user = self.create_user(
            email,
            password=password,
            **extra_fields,
        )
        user.is_superuser = True
        user.is_active = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractUser):
    email = models.EmailField(
        verbose_name="email address",
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = (
        "first_name",
        "last_name",
    )

    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Usuários"

    def __str__(self):
        return self.email

rigueira/core/models.py
from core.util import get_upload_path
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

USER_TYPE_CHOICES = (
    (1, 'student'),
    (2, 'teacher'),
    (3, 'parent'),
    (4, 'admin'),
)


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('O email é obrigatório!')

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        user = self.create_user(
            email,
            password=password,
            **extra_fields,
        )
        user.is_superuser = True
        user.is_active = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractUser):
    username = None
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    avatar = models.ImageField(blank=True, upload_to=get_upload_path)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    user_type = models.PositiveSmallIntegerField(
        choices=USER_TYPE_CHOICES,
        default=1,
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = (
        'first_name',
        'last_name',
    )

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.email

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ano_letivo = models.CharField(max_length=2)
    school = models.CharField(max_length=200)

    def __str__(self):
        return self.user.full_name


@receiver(post_save, sender=User)
def save_student(sender, instance, created, **kwargs):
    if created and instance.user_type == 1:
        Student.objects.create(user=instance)

rigueira/core/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.utils.translation import gettext_lazy as _

from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
        )
        labels = {
            'first_name': 'Primeiro Nome',
            'last_name': 'Último Nome',
            'username': 'E-mail',
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
        )


UserModel = get_user_model()


class AuthenticationForm(forms.Form):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    email/password logins.
    """

    email = forms.EmailField(
        label=_('Email address'),
        max_length=254,
        widget=forms.EmailInput(attrs={'autofocus': True}),
    )
    password = forms.CharField(
        label=_('Password'),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )

    error_messages = {
        'invalid_login': _(
            'Please enter a correct %(username)s and password. Note that both '
            'fields may be case-sensitive.'
        ),
        'inactive': _('This account is inactive.'),
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)

        self.username_field = UserModel._meta.get_field(
            UserModel.USERNAME_FIELD
        )

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email is not None and password:
            self.user_cache = authenticate(
                self.request, email=email, password=password
            )
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in. This is a policy setting,
        independent of end-user authentication. This default behavior is to
        allow login by active users, and reject login by inactive users.
        If the given user cannot log in, this method should raise a
        ``forms.ValidationError``.
        If the given user may log in, this method should return None.
        """
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user(self):
        return self.user_cache

    def get_invalid_login_error(self):
        return forms.ValidationError(
            self.error_messages['invalid_login'],
            code='invalid_login',
            params={'username': self.username_field.verbose_name},
        )

rigueira/core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'core/home.html')

rigueira/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Rigueira">
        <meta name="author"
              content="Gabriel Torres Gomes  - gabrieltggv29@gmail.com">
        <!-- Favicon -->
        <link href="img/favicon.ico" rel="icon" />
        <link rel="stylesheet"
              type="text/css"
              media="screen"
              href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet"
              type="text/css"
              media="screen"
              href="{% static 'css/core.css' %}">
        <link rel="stylesheet"
              type="text/css"
              media="screen"
              href="{% static 'css/reset.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Mukta:wght@400;700&family=Saira&display=swap"
              rel="stylesheet">
        <title>
            {% block title %}{% endblock %}
        </title>
    </head>
    <body>
        <!-- Messages -->
        <div id="messages" class="container p-2 d-none"></div>
        <!-- HtmxCanvas -->
        {% block body %}{% endblock %}
        <script src="{% static 'bootstrap/js/bootstrap.min.js'%}" defer></script>
        <script src="{% static 'htmx/htmx.min.js' %}" defer></script>
        <script src="{% static 'chart/chart.min.js' %}" defer></script>
    </body>
</html>

rigueira/core/templates/core/home.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block body %}
    <div class="container-fluid g-0">
        <div class='row g-0'>
            <div class="col-2 col-sm-1">
                <div id="sidebar" class="d-flex flex-column flex-shrink-0 bg-light">
                    <a href="/"
                       class="d-block px-3 link-dark text-decoration-none"
                       title=""
                       data-bs-toggle="tooltip"
                       data-bs-placement="right"
                       data-bs-original-title="Icon-only">
                        <img src="{% static 'img/logo_rigueira.svg' %}"
                             alt="Rigueira acompanhamento escolar"
                             style='width: 40px; height: 55px'>
                        <span class="visually-hidden">Icon-only</span>
                    </a>
                    <ul class="nav nav-pills nav-flush flex-column mb-auto text-center">
                        <li>
                            <a href="#"
                               class="nav-link py-3 border-bottom"
                               title=""
                               data-bs-toggle="tooltip"
                               hx-get="{% url 'feedback:dashboard' %}"
                               hx-target="#htmxCanvas"
                               data-bs-placement="right"
                               data-bs-original-title="Dashboard">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                    <path d="M447.1 0h-384c-35.25 0-64 28.75-64 63.1v287.1c0 35.25 28.75 63.1 64 63.1h96v83.98c0 9.836 11.02 15.55 19.12 9.7l124.9-93.68h144c35.25 0 64-28.75 64-63.1V63.1C511.1 28.75 483.2 0 447.1 0zM464 352c0 8.75-7.25 16-16 16h-160l-80 60v-60H64c-8.75 0-16-7.25-16-16V64c0-8.75 7.25-16 16-16h384c8.75 0 16 7.25 16 16V352z"/>
                                </svg>
                            </a>
                        </li>
                        <li>
                            <a href="#"
                               class="nav-link py-3 border-bottom"
                               title=""
                               data-bs-toggle="tooltip"
                               data-bs-placement="right"
                               data-bs-original-title="Orders">
                                <svg class="bi" width="24" height="24" role="img" aria-label="Orders">
                                    <use xlink:href="#table"></use>
                                </svg>
                            </a>
                        </li>
                        <li>
                            <a href="#"
                               class="nav-link py-3 border-bottom"
                               title=""
                               data-bs-toggle="tooltip"
                               data-bs-placement="right"
                               data-bs-original-title="Products">
                                <svg class="bi" width="24" height="24" role="img" aria-label="Products">
                                    <use xlink:href="#grid"></use>
                                </svg>
                            </a>
                        </li>
                        <li>
                            <a href="#"
                               class="nav-link py-3 border-bottom"
                               title=""
                               data-bs-toggle="tooltip"
                               data-bs-placement="right"
                               data-bs-original-title="Customers">
                            </a>
                        </li>
                    </ul>
                    <div class="dropdown border-top">
                        <a href="#"
                           class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle"
                           id="dropdownUser3"
                           data-bs-toggle="dropdown"
                           aria-expanded="false">
                            <img src="{{ request.user.avatar.url }}"
                                 alt="mdo"
                                 width="24"
                                 height="24"
                                 class="rounded-circle">
                        </a>
                        <ul class="dropdown-menu text-small shadow"
                            aria-labelledby="dropdownUser3"
                            style="">
                            <li>
                                <a class="dropdown-item" href="#">New project...</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">Settings</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">Profile</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'logout' %}">Sign out</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <main id="htmxCanvas" class="col-10 col-sm-11 ps-2">
            </main>
        </div>
    </div>
{% endblock %}

rigueira/core/templates/core/home_alter.html
{% extends "core/base.html" %}
{% load static %}

{% block title %} Home {% endblock %}

{% block body %}
<div class="container-fluid g-0 mb-5">
    {% if user.is_authenticated %}
                    <h1>So para entender</h1>
                    <p>
                        <a href="/logout">Log Out</a>
                    </p>
                {% endif %}
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://br.depositphotos.com/stock-photos/p%C3%B4r-do-sol.html" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="https://br.depositphotos.com/stock-photos/p%C3%B4r-do-sol.html" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="https://educador.brasilescola.uol.com.br/estrategias-ensino/como-produzir-imagens-reais-virtuais-sala-aula.html" class="d-block w-100" alt="...">
        </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

<section class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10 col-xl-8 text-center">
            <h3 class="mb-4">Testimonials</h3>
            <p class="mb-4 pb-2 mb-md-5 pb-md-0">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit, error amet
                numquam iure provident voluptate esse quasi, veritatis totam voluptas nostrum
                quisquam eum porro a pariatur veniam.
            </p>
        </div>
    </div>
  
    <div class="row text-center">
        <div class="col-md-4 mb-5 mb-md-0">
            <div class="card testimonial-card">
                <div class="card-up" style="background-color: #9d789b;"></div>
                <div class="avatar mx-auto bg-white">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).webp"
                    class="rounded-circle img-fluid" />
                </div>
                <div class="card-body">
                    <h4 class="mb-4">Maria Smantha</h4>
                    <hr />
                    <p class="dark-grey-text mt-4">
                    <i class="fas fa-quote-left pe-2"></i>Lorem ipsum dolor sit amet eos adipisci,
                    consectetur adipisicing elit.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-5 mb-md-0">
            <div class="card testimonial-card">
                <div class="card-up" style="background-color: #7a81a8;"></div>
                <div class="avatar mx-auto bg-white">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(2).webp"
                    class="rounded-circle img-fluid" />
                </div>
                <div class="card-body">
                    <h4 class="mb-4">Lisa Cudrow</h4>
                    <hr />
                    <p class="dark-grey-text mt-4">
                    <i class="fas fa-quote-left pe-2"></i>Neque cupiditate assumenda in maiores
                    repudi mollitia architecto.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-0">
            <div class="card testimonial-card">
                <div class="card-up" style="background-color: #6d5b98;"></div>
                <div class="avatar mx-auto bg-white">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).webp"
                    class="rounded-circle img-fluid" />
                </div>
                <div class="card-body">
                    <h4 class="mb-4">John Smith</h4>
                    <hr />
                    <p class="dark-grey-text mt-4">
                    <i class="fas fa-quote-left pe-2"></i>Delectus impedit saepe officiis ab
                    aliquam repellat rem unde ducimus.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<footer class="bg-light text-center text-white">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Facebook -->
        <a
          class="btn btn-primary btn-floating m-1"
          style="background-color: #3b5998;"
          href="#!"
          role="button"
          ><i class="fab fa-facebook-f"></i
        ></a>
  
        <!-- Twitter -->
        <a
          class="btn btn-primary btn-floating m-1"
          style="background-color: #55acee;"
          href="#!"
          role="button"
          ><i class="fab fa-twitter"></i
        ></a>
  
        <!-- Google -->
        <a
          class="btn btn-primary btn-floating m-1"
          style="background-color: #dd4b39;"
          href="#!"
          role="button"
          ><i class="fab fa-google"></i
        ></a>
  
        <!-- Instagram -->
        <a
          class="btn btn-primary btn-floating m-1"
          style="background-color: #ac2bac;"
          href="#!"
          role="button"
          ><i class="fab fa-instagram"></i
        ></a>
  
        <!-- Linkedin -->
        <a
          class="btn btn-primary btn-floating m-1"
          style="background-color: #0082ca;"
          href="#!"
          role="button"
          ><i class="fab fa-linkedin-in"></i
        ></a>
        <!-- Github -->
        <a
          class="btn btn-primary btn-floating m-1"
          style="background-color: #333333;"
          href="#!"
          role="button"
          ><i class="fab fa-github"></i
        ></a>
      </section>
      <!-- Section: Social media -->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="https://mdbootstrap.com/">Rigueira</a>
    </div>
    <!-- Copyright -->
</footer>
{% endblock %}

rigueira/core/templates/core/login.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Login{% endblock %}
{% block body %}
        <div class="row">
            <div class="d-flex flex-column align-items-center justify-content-center col-md-7 col-sm-12 g-0">
                <div class="card_login">
                    {% if form.errors %}<p>{{ form.non_field_errors }}</p>{% endif %}
                    <h1 class="m-5 ps-5">Login</h1>
                    <form action="{% url 'login' %}" method="POST" class="needs-valitation">
                        {% csrf_token %}
                        <div class="form-goup">
                            <label for="email" class="form-label">Email</label>
                            <input type="email"
                                   class="form-control"
                                   name="email"
                                   id="email"
                                   placeholder="email">
                        </div>
                        <div class="form-group my-1">
                            <label for="password" class="form-label">Senha</label>
                            <input type="password"
                                   class="form-control"
                                   name="password"
                                   id="password"
                                   placeholder="password">
                        </div>
                        <button type="submit" class="btn btn-success btn-block my-4">Entrar</button>
                    </form>
                </div>
            </div>
            <picture class="col-4 g-0">
                <img src="{% static 'img/logo_rigueira.svg' %}"
                     class="img-fluid"
                     alt="Rigueira">
            </picture>
        </div>
{% endblock %}